/* ==========================================
 * TABLE: ATG_3627_DT_ENTRIES
 * ========================================== */
CREATE TABLE "ATG_3627_DT_ENTRIES"(
 "ENTRY_ID" IDENTITY DEFAULT '0',
 "JOB" CHAR(20) NOT NULL ,
 "SUFFIX" CHAR(3),
 "SEQUENCE" CHAR(6) NOT NULL ,
 "WORKCENTER" CHAR(4) NOT NULL ,
 "EMPLOYEE" CHAR(5) NOT NULL ,
 "CATEGORY" CHAR(4) NOT NULL ,
 "DESCRIPTION" CHAR(30),
 "QUANTITY" DOUBLE NOT NULL ,
 "NOTES" LONGVARCHAR,
 "SHIFT" CHAR(1) NOT NULL ,
 "DATE_ENTERED" DATETIME NOT NULL ,
 "USER_ENTERED" CHAR(8),
 "DATE_MODIFIED" DATETIME,
 "USER_MODIFIED" CHAR(8),
 PRIMARY KEY ("ENTRY_ID"),
 UNIQUE ("ENTRY_ID"));


